defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpEnableInlining: true

yarnPath: .yarn/releases/yarn-4.0.0-rc.35.cjs
