name: GitHub Versioning
on:
  push:
    branches: [main]
concurrency: versioning-${{ github.ref }}
jobs:
  ci:
    name: CI
    uses: ./.github/workflows/continuous-integration.yml
  version:
    name: Version
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' # https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-797125425
    outputs:
      trigger-deploy: ${{ steps.changesets.outputs.hasChangesets == 'false' && steps.commit.outputs.result == 'true' }}
    strategy:
      matrix:
        node-version: [19.1.0]
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # ratchet:actions/checkout@v3
      - uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048 # ratchet:actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db # ratchet:actions/setup-node@v1
        id: generate-token
        with:
          application_id: ${{ secrets.GENERATE_TOKEN_APPLICATION_ID }}
          application_private_key: ${{ secrets.GENERATE_TOKEN_PRIVATE_KEY }}
      - uses: changesets/action@5f3b898718761af42fe162af3258e4145d07be24 # ratchet:changesets/action@v1
        id: changesets
        with:
          version: yarn change:version
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
      - uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0 #ratchet:actions/github-script@v6
        id: commit
        with:
          script: |
            const commit = await github.rest.git.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
            });
            const deploy = commit.data.message.startsWith("Release changes\n") && commit.data.author.name === "github-actions[bot]";
            return deploy;
  start-deploy:
    name: Start Deployment
    needs: [ci, version]
    if: needs.version.outputs.trigger-deploy == 'true'
    uses: ./.github/workflows/continuous-deployment.yml
    secrets: inherit
